ALTER TABLE `REPORT_HISTORY` 
ADD COLUMN `startDt` TIMESTAMP NULL AFTER `updatedBy`,
ADD COLUMN `endDt` TIMESTAMP NULL AFTER `startDt`,
ADD COLUMN `duration` FLOAT NULL AFTER `endDt`,
ADD COLUMN `recordCount` INT(11) NULL AFTER `duration`;

