-- Seed data for AnzscoDisambiguationOption, generated from anzsco-module-mapping.csv.
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('133', 'Which of these best describes your job?', 'CONS', 'Construction Trades', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('133', 'Which of these best describes your job?', 'FORE', 'ForestryTimbermill', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('133', 'Which of these best describes your job?', 'IMAR', 'Industrial Manufacturing, Assembly and repair', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('133', 'Which of these best describes your job?', 'MINE', 'Miners/Quarrymen', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('133', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('133', 'Which of these best describes your job?', 'STOR', 'Store person', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('134', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('134', 'Which of these best describes your job?', 'TEAC', 'Teaching', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('139', 'Which of these best describes your job?', 'FIRE', 'Firefighter', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('139', 'Which of these best describes your job?', 'LABC', 'Lab worker Chemist', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('139', 'Which of these best describes your job?', 'MLTY', 'Military', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('139', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('139', 'Which of these best describes your job?', 'POLI', 'Police', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('141', 'Which of these best describes your job?', 'FOOD', 'Food Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('141', 'Which of these best describes your job?', 'JANI', 'Caretaker/Janitor', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('141', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('142', 'Which of these best describes your job?', 'HAIR', 'Hairdresser/Beauty Therapist', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('142', 'Which of these best describes your job?', 'RETA', 'Retail Workers', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('149', 'Which of these best describes your job?', 'ANIM', 'Animal Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('149', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('149', 'Which of these best describes your job?', 'RAIL', 'Railway', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('211', 'Which of these best describes your job?', 'ARTF', 'Artist/Film Processing', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('211', 'Which of these best describes your job?', 'CERA', 'Ceramics Glass Prod', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('211', 'Which of these best describes your job?', 'MUSI', 'Musician/Entertainer', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('212', 'Which of these best describes your job?', 'MUSI', 'Musician/Entertainer', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('212', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('231', 'Which of these best describes your job?', 'AIRT', 'Air Transport Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('231', 'Which of these best describes your job?', 'SHIP', 'Shipping/Fishing', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('232', 'Which of these best describes your job?', 'ARTF', 'Artist/Film Processing', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('232', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('233', 'Which of these best describes your job?', 'CHEM', 'Chemical Pharmaceutical Manufacturing', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('233', 'Which of these best describes your job?', 'HLTH', 'Health Workers', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('233', 'Which of these best describes your job?', 'LABC', 'Lab worker Chemist', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('233', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('234', 'Which of these best describes your job?', 'ARTF', 'Artist/Film Processing', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('234', 'Which of these best describes your job?', 'FARM', 'Farmer', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('234', 'Which of these best describes your job?', 'FOOD', 'Food Workers', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('234', 'Which of these best describes your job?', 'FORE', 'ForestryTimbermill', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('234', 'Which of these best describes your job?', 'HLTH', 'Health Workers', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('234', 'Which of these best describes your job?', 'JANI', 'Caretaker/Janitor', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('234', 'Which of these best describes your job?', 'LABC', 'Lab worker Chemist', 6);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('234', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 7);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('249', 'Which of these best describes your job?', 'ARTF', 'Artist/Film Processing', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('249', 'Which of these best describes your job?', 'MUSI', 'Musician/Entertainer', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('249', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('249', 'Which of these best describes your job?', 'TEAC', 'Teaching', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('251', 'Which of these best describes your job?', 'HLTH', 'Health Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('251', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('311', 'Which of these best describes your job?', 'ANIM', 'Animal Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('311', 'Which of these best describes your job?', 'FARM', 'Farmer', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('311', 'Which of these best describes your job?', 'FOOD', 'Food Workers', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('311', 'Which of these best describes your job?', 'HLTH', 'Health Workers', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('311', 'Which of these best describes your job?', 'LABC', 'Lab worker Chemist', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('311', 'Which of these best describes your job?', 'SHIP', 'Shipping/Fishing', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('312', 'Which of these best describes your job?', 'CONS', 'Construction Trades', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('312', 'Which of these best describes your job?', 'FAMM', 'Fitter and Maintenance Mechanic', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('312', 'Which of these best describes your job?', 'IMAR', 'Industrial Manufacturing, Assembly and repair', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('312', 'Which of these best describes your job?', 'MINE', 'Miners/Quarrymen', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('312', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('312', 'Which of these best describes your job?', 'PRMM', 'Metal Refining/Smelting', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('322', 'Which of these best describes your job?', 'ANIM', 'Animal Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('322', 'Which of these best describes your job?', 'FOUN', 'Foundry', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('322', 'Which of these best describes your job?', 'MFAC', 'Metal Finishing & Coating', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('322', 'Which of these best describes your job?', 'WELD', 'Welder', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('323', 'Which of these best describes your job?', 'AIRT', 'Air Transport Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('323', 'Which of these best describes your job?', 'FAMM', 'Fitter and Maintenance Mechanic', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('323', 'Which of these best describes your job?', 'FOUN', 'Foundry', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('323', 'Which of these best describes your job?', 'IMAR', 'Industrial Manufacturing, Assembly and repair', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('324', 'Which of these best describes your job?', 'MECH', 'Mechanic/Panel Beater', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('324', 'Which of these best describes your job?', 'MFAC', 'Metal Finishing & Coating', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('324', 'Which of these best describes your job?', 'UPHO', 'Upholstery', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('341', 'Which of these best describes your job?', 'CONS', 'Construction Trades', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('341', 'Which of these best describes your job?', 'FAMM', 'Fitter and Maintenance Mechanic', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('342', 'Which of these best describes your job?', 'FAMM', 'Fitter and Maintenance Mechanic', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('342', 'Which of these best describes your job?', 'LINE', 'Power Line / Station', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('342', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('361', 'Which of these best describes your job?', 'ANIM', 'Animal Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('361', 'Which of these best describes your job?', 'HLTH', 'Health Workers', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('362', 'Which of these best describes your job?', 'FLOR', 'Florist', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('362', 'Which of these best describes your job?', 'GARD', 'Gardener Groundskeeper', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('363', 'Which of these best describes your job?', 'ANIM', 'Animal Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('363', 'Which of these best describes your job?', 'FARM', 'Farmer', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('393', 'Which of these best describes your job?', 'SHOE', 'Shoes and leather goods', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('393', 'Which of these best describes your job?', 'TEXT', 'Textiles', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('393', 'Which of these best describes your job?', 'UPHO', 'Upholstery', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('394', 'Which of these best describes your job?', 'CONS', 'Construction Trades', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('394', 'Which of these best describes your job?', 'IMAR', 'Industrial Manufacturing, Assembly and repair', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'ARTF', 'Artist/Film Processing', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'CHEM', 'Chemical Pharmaceutical Manufacturing', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'HAIR', 'Hairdresser/Beauty Therapist', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'IMAR', 'Industrial Manufacturing, Assembly and repair', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'LINE', 'Power Line / Station', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'OPET', 'Oil/Petroleum Industry', 6);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'PRIN', 'Printing', 7);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'RETA', 'Retail Workers', 8);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'RUBB', 'Rubber or plastic Industry', 9);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('399', 'Which of these best describes your job?', 'SHIP', 'Shipping/Fishing', 10);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('411', 'Which of these best describes your job?', 'HLTH', 'Health Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('411', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('423', 'Which of these best describes your job?', 'HLTH', 'Health Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('423', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('431', 'Which of these best describes your job?', 'FOOD', 'Food Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('431', 'Which of these best describes your job?', 'RETA', 'Retail Workers', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('441', 'Which of these best describes your job?', 'FIRE', 'Firefighter', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('441', 'Which of these best describes your job?', 'MLTY', 'Military', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('441', 'Which of these best describes your job?', 'POLI', 'Police', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('442', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('442', 'Which of these best describes your job?', 'POLI', 'Police', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('451', 'Which of these best describes your job?', 'AIRT', 'Air Transport Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('451', 'Which of these best describes your job?', 'DRIV', 'Driver', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('451', 'Which of these best describes your job?', 'FUNR', 'Funeral Workers', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('451', 'Which of these best describes your job?', 'HAIR', 'Hairdresser/Beauty Therapist', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('451', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('451', 'Which of these best describes your job?', 'RETA', 'Retail Workers', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('451', 'Which of these best describes your job?', 'TEAC', 'Teaching', 6);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('452', 'Which of these best describes your job?', 'ANIM', 'Animal Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('452', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('452', 'Which of these best describes your job?', 'TEAC', 'Teaching', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('561', 'Which of these best describes your job?', 'DRIV', 'Driver', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('561', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('561', 'Which of these best describes your job?', 'RDSD', 'RoadsideWorker', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('591', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('591', 'Which of these best describes your job?', 'STOR', 'Store person', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('599', 'Which of these best describes your job?', 'DRIV', 'Driver', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('599', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('599', 'Which of these best describes your job?', 'PEST', 'Pesticide Users', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('599', 'Which of these best describes your job?', 'RAIL', 'Railway', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('599', 'Which of these best describes your job?', 'RDSD', 'RoadsideWorker', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('599', 'Which of these best describes your job?', 'SEWG', 'Sewage and Water Worker', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('621', 'Which of these best describes your job?', 'PESA', 'Petrol Station Attendant', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('621', 'Which of these best describes your job?', 'RDSD', 'RoadsideWorker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('621', 'Which of these best describes your job?', 'RETA', 'Retail Workers', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('621', 'Which of these best describes your job?', 'WAMA', 'Waste Management', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('639', 'Which of these best describes your job?', 'ANIM', 'Animal Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('639', 'Which of these best describes your job?', 'RDSD', 'RoadsideWorker', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('639', 'Which of these best describes your job?', 'RETA', 'Retail Workers', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'CERA', 'Ceramics Glass Prod', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'CHEM', 'Chemical Pharmaceutical Manufacturing', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'HLTH', 'Health Workers', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'IMAR', 'Industrial Manufacturing, Assembly and repair', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'LEAT', 'Leather Tanning', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'MFAC', 'Metal Finishing & Coating', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'OFFW', 'Office Worker', 6);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'PRIN', 'Printing', 7);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'RUBB', 'Rubber or plastic Industry', 8);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'SHOE', 'Shoes and leather goods', 9);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('711', 'Which of these best describes your job?', 'TEXT', 'Textiles', 10);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('712', 'Which of these best describes your job?', 'CONS', 'Construction Trades', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('712', 'Which of these best describes your job?', 'FAMM', 'Fitter and Maintenance Mechanic', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('712', 'Which of these best describes your job?', 'IMAR', 'Industrial Manufacturing, Assembly and repair', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('712', 'Which of these best describes your job?', 'MINE', 'Miners/Quarrymen', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('712', 'Which of these best describes your job?', 'RAIL', 'Railway', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('712', 'Which of these best describes your job?', 'RDSD', 'RoadsideWorker', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('712', 'Which of these best describes your job?', 'SEWG', 'Sewage and Water Worker', 6);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('721', 'Which of these best describes your job?', 'AIRT', 'Air Transport Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('721', 'Which of these best describes your job?', 'DRIV', 'Driver', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('721', 'Which of these best describes your job?', 'FARM', 'Farmer', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('721', 'Which of these best describes your job?', 'FORE', 'ForestryTimbermill', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('721', 'Which of these best describes your job?', 'RAIL', 'Railway', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('721', 'Which of these best describes your job?', 'ROAD', 'RoadConstruction', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('721', 'Which of these best describes your job?', 'STOR', 'Store person', 6);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('731', 'Which of these best describes your job?', 'DRIV', 'Driver', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('731', 'Which of these best describes your job?', 'RAIL', 'Railway', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('733', 'Which of these best describes your job?', 'AIRT', 'Air Transport Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('733', 'Which of these best describes your job?', 'DRIV', 'Driver', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('811', 'Which of these best describes your job?', 'CLNR', 'Cleaner', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('811', 'Which of these best describes your job?', 'DRYC', 'Dry Cleaner', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('821', 'Which of these best describes your job?', 'CONS', 'Construction Trades', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('821', 'Which of these best describes your job?', 'RAIL', 'Railway', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('821', 'Which of these best describes your job?', 'ROAD', 'RoadConstruction', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('821', 'Which of these best describes your job?', 'SEWG', 'Sewage and Water Worker', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('832', 'Which of these best describes your job?', 'FOOD', 'Food Workers', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('832', 'Which of these best describes your job?', 'IMAR', 'Industrial Manufacturing, Assembly and repair', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('839', 'Which of these best describes your job?', 'CERA', 'Ceramics Glass Prod', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('839', 'Which of these best describes your job?', 'CHEM', 'Chemical Pharmaceutical Manufacturing', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('839', 'Which of these best describes your job?', 'FORE', 'ForestryTimbermill', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('839', 'Which of these best describes your job?', 'IMAR', 'Industrial Manufacturing, Assembly and repair', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('839', 'Which of these best describes your job?', 'LABC', 'Lab worker Chemist', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('839', 'Which of these best describes your job?', 'LEAT', 'Leather Tanning', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('839', 'Which of these best describes your job?', 'RUBB', 'Rubber or plastic Industry', 6);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('839', 'Which of these best describes your job?', 'SHOE', 'Shoes and leather goods', 7);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('839', 'Which of these best describes your job?', 'TEXT', 'Textiles', 8);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('839', 'Which of these best describes your job?', 'WAMA', 'Waste Management', 9);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('843', 'Which of these best describes your job?', 'ANIM', 'Animal Worker', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('843', 'Which of these best describes your job?', 'FARM', 'Farmer', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('843', 'Which of these best describes your job?', 'FORE', 'ForestryTimbermill', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('843', 'Which of these best describes your job?', 'GARD', 'Gardener Groundskeeper', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('843', 'Which of these best describes your job?', 'PEST', 'Pesticide Users', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('891', 'Which of these best describes your job?', 'DRIV', 'Driver', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('891', 'Which of these best describes your job?', 'STOR', 'Store person', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('899', 'Which of these best describes your job?', 'JANI', 'Caretaker/Janitor', 0);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('899', 'Which of these best describes your job?', 'LINE', 'Power Line / Station', 1);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('899', 'Which of these best describes your job?', 'MECH', 'Mechanic/Panel Beater', 2);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('899', 'Which of these best describes your job?', 'PRIN', 'Printing', 3);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('899', 'Which of these best describes your job?', 'RAIL', 'Railway', 4);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('899', 'Which of these best describes your job?', 'RDSD', 'RoadsideWorker', 5);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('899', 'Which of these best describes your job?', 'RETA', 'Retail Workers', 6);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('899', 'Which of these best describes your job?', 'SHIP', 'Shipping/Fishing', 7);
INSERT INTO AnzscoDisambiguationOption (anzscoPrefix, questionText, moduleCode, optionLabel, sequence) VALUES ('899', 'Which of these best describes your job?', 'WAMA', 'Waste Management', 8);
