package org.occideas.entity;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * Interview generated by hbm2java
 */
@Entity
public class Interview implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id @GeneratedValue
	private long idinterview;
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="module_idNode",referencedColumnName="idNode")
	private Module module;
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="fragment_idNode",referencedColumnName="idNode")
	private Fragment fragment;
	
	@OneToMany(mappedBy="interview")
	private List<InterviewQuestionAnswer> interviewQuestionAnswers;
	
	private String referenceNumber;

	public Interview() {
	}
	
	public Interview(long idinterview) {
		this.idinterview = idinterview;
	}	

	public long getIdinterview() {
		return this.idinterview;
	}

	public void setIdinterview(long idinterview) {
		this.idinterview = idinterview;
	}

	public List<InterviewQuestionAnswer> getInterviewQuestionAnswers() {
		return interviewQuestionAnswers;
	}

	public void setInterviewQuestionAnswers(List<InterviewQuestionAnswer> interviewQuestionAnswers) {
		this.interviewQuestionAnswers = interviewQuestionAnswers;
	}

	public Module getModule() {
		return module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	public String getReferenceNumber() {
		return referenceNumber;
	}

	public void setReferenceNumber(String referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public Fragment getFragment() {
		return fragment;
	}

	public void setFragment(Fragment fragment) {
		this.fragment = fragment;
	}

}
